name: Cypress Tests

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cy:run
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HTTP_BASIC_AUTH_USERNAME: ${{ secrets.HTTP_BASIC_AUTH_USERNAME }}
          HTTP_BASIC_AUTH_PASSWORD: ${{ secrets.HTTP_BASIC_AUTH_PASSWORD }}